---
# Roles: selinux
# selinux - Change policy and state of SELinux
# http://docs.ansible.com/ansible/latest/selinux_module.html

# Configures the SELinux mode and policy.
# A reboot may be required after usage.
# Ansible will not issue this reboot but will let you know when it is required.

# SELinux is a security extension of CentOS that should provide extended security.
# In my opinion you don't need it to configure a secure system,
# and it usually causes more problems than advantages
# (think of it after you have done a week of trouble-shooting
# because some service wasn't working as expected,
# and then you find out that everything was ok,
# only SELinux was causing the problem).
# Therefore I disable it (this is a must if you want to install any control panel
# such as Vesta Control Panel, ISPConfig later on).

# Set true to one of the following variables.
selinux_enforcing_enabled: false
selinux_permissive_enabled: false
selinux_disabled: true
