---
- name: Set up the Nodesource RPM directory for Node.js > 0.10.
  set_fact:
    nodejs_rhel_rpm_dir: "pub_{{ nodejs_version }}"
  when: nodejs_version != '0.10'

- name: Set up the Nodesource RPM variable for Node.js == 0.10.
  set_fact:
    nodejs_rhel_rpm_dir: "pub"
  when: nodejs_version == '0.10'

- name: Import Nodesource RPM key (CentOS < 7).
  rpm_key:
    key: http://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_distribution_major_version|int < 7

- name: Import Nodesource RPM key (CentOS 7+)..
  rpm_key:
    key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_distribution_major_version|int >= 7

- name: Add Nodesource repositories for Node.js (CentOS < 7).
  yum:
    name: "http://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present
  when: ansible_distribution_major_version|int < 7

- name: Add Nodesource repositories for Node.js (CentOS 7+).
  yum:
    name: "https://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present
  when: ansible_distribution_major_version|int >= 7

- name: Ensure Node.js and npm are installed.
  yum: "name=nodejs-{{ nodejs_version[0] }}.* state=present enablerepo='epel,nodesource'"

- name: Checking nodejs version
  command: node -v
  register: command_result

- name: nodejs version
  debug: msg="{{ command_result.stdout }}"

- name: Checking npm version
  command: npm -v
  register: command_result

- name: npm version
  debug: msg="{{ command_result.stdout }}"


- name: Install Grunt node.js package globally
  command: npm install -g grunt-cli

- name: Checking Grunt version
  command: npm -v
  register: command_result

- name: Grunt version
  debug: msg="{{ command_result.stdout }}"


- name: Install "coffee-script" node.js package globally.
  npm:
    name: coffee-script
    global: yes

- name: Checking coffee-script version
  command: coffee -v
  register: command_result

- name: coffee-script version
  debug: msg="{{ command_result.stdout }}"


- name: Install bower node.js package globally
  command: npm install -g bower

- name: Checking bower version
  command: bower -v
  register: command_result

- name: bower version
  debug: msg="{{ command_result.stdout }}"


- name: Install Yarn RPM package repository.
  command: wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo

- name: Install Yarn
  yum:
    name: yarn
    state: present

- name: Checking Yarn version
  command: yarn -v
  register: command_result

- name: Yarn version
  debug: msg="{{ command_result.stdout }}"


- name: Install graceful-fs node.js package globally
  command: npm install -g graceful-fs graceful-fs@latest

- name: Install gulp node.js package globally
  command: npm install gulp -g

- name: Checking gulp version
  command: gulp -v
  register: command_result

- name: gulp version
  debug: msg="{{ command_result.stdout }}"
